//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iTunesSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class analytic
    {
        public int trackId { get; set; }
        public int hitCount { get; set; }
    
        public virtual hit hit { get; set; }
    }
}
